/** English is the source language; every other dictionary mirrors these keys. */
export const en = {
  "lang.switch": "Language",

  "nav.home": "Home",
  "nav.spec": "Specification",
  "nav.generate": "Generate",
  "nav.validate": "Validate",
  "nav.explain": "Legacy explainer",
  "nav.tools": "Tools",
  "nav.faq": "FAQ",
  "nav.imprint": "Legal notice",
  "nav.skip": "Skip to content",
  "nav.main": "Main navigation",

  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.download": "Download",
  "common.back": "Back",
  "common.next": "Next",
  "common.optional": "optional",
  "common.add": "Add",
  "common.remove": "Remove",
  "common.print": "Print",
  "common.of": "of",
  "generate.languages_none": "None chosen",
  "common.hint_label": "What goes in this field",
  "common.hint_example": "Example:",
  "common.invalid_utf8": "The selected file is not valid UTF-8.",

  "footer.funding":
    "This site is run by Skalvar Technologies UG (haftungsbeschränkt) in Wismar, Germany, which earns its money developing IT security software. The format, the library and this site work without our products and without us.",
  "footer.privacy":
    "No tracking, no cookies, no analytics, no external fonts. Everything you type stays in your browser.",
  "footer.licence": "Specification and schema: CC0-1.0. Library and site: Apache-2.0.",

  "home.title": "State how you handle vulnerability reports.",
  "home.lead": "The CVD Policy Format is a small JSON file at an explicitly advertised HTTPS URI. It states which assets accept reports, which testing rules the publisher states, and how to report. Machines can read it. So can people.",
  "home.what_title": "In sixty seconds",
  "home.what_body": "security.txt names a contact. V1 adds a publisher statement about reportable assets, testing rules, reporting preferences and the response process. It does not prove ownership or control, grant legal authorization, or guarantee safe harbor. A tool can evaluate the statement before it sends a request.",
  "home.privacy_title": "Nothing leaves your device",
  "home.privacy_body":
    "The generator, the validator and the explainer run entirely in your browser. There is no backend, no upload and no request to any other domain. Open your network tab and check.",
  "home.cta_generate": "Create a file",
  "home.cta_validate": "Check a file",
  "home.cta_spec": "Read the specification",
  "home.example_title": "What it looks like",
  "home.example_caption": "A complete document for an organisation that accepts reports but does not invite testing.",
  "home.steps_title": "Three steps",
  "home.step_1": "Create and download the V1 policy document.",
  "home.step_2": "Publish it at the exact HTTPS URI you selected.",
  "home.step_3": "Advertise that URI with one CVD-Policy field in /.well-known/security.txt.",
  "home.not_title": "What this is not",
  "home.not_1": "Not a replacement for security.txt — it adds one field to it.",
  "home.not_2": "Not proof of regulatory conformity, including under the CRA.",
  "home.not_3": "Not legal authorization or proof of ownership. It records a publisher statement, nothing more.",
  "home.not_4": "Not a rating. No score, no maturity level, no comparison.",
  "home.v1_notice_intro": "Experimental V1 implementation of",
  "home.v1_notice_change": "The proposed field and media type may change.",

  "spec.title": "Specification",
  "spec.lead": "Version 1 candidate, the format implemented by the current generator and validator. Licensed CC0-1.0.",
  "spec.versions_note": "Versions 0.1 and 0.2 remain available as frozen legacy formats.",
  "spec.package_versions_note":
    "Package versions are not format versions. @cvd-policy/core 0.5.0-rc.1 implements the experimental format V1; cvd_policy inside a document selects the document rules.",
  "spec.schema": "JSON Schema",
  "spec.v1_notice_intro": "This is the experimental V1 candidate corresponding to",
  "spec.v1_notice_change": "It is not an RFC or IETF consensus and may change.",
  "spec.translation_notice": "The English specification is normative. The German translation is informative.",
  "spec.legacy_title": "Legacy 0.x",
  "spec.legacy_body": "Existing 0.1 and 0.2 documents keep their frozen specifications and schemas. The report-0.1 profile is also legacy and is not a V1 report transport.",

  "notfound.title": "Page not found",
  "notfound.lead":
    "That address does not match any page here. The file you were looking for may live on someone else’s domain — this site only hosts the format itself.",

  "generate.title": "Generate a policy",
  "generate.lead": "What should reporters know about dealing with your organisation?",
  "generate.mode_quick": "Quick",
  "generate.mode_quick_help": "Five questions, a valid document in under two minutes.",
  "generate.mode_full": "Complete",
  "generate.mode_full_help": "Every field the format defines.",
  "generate.preview": "Live preview",
  "generate.preview_note": "Built in your browser as you type.",
  "generate.step_org": "Organisation",
  "generate.step_posture": "Posture",
  "generate.step_contact": "Contact",
  "generate.step_scope": "Scope",
  "generate.step_testing": "Testing rules",
  "generate.step_report": "Report requirements",
  "generate.step_disclosure": "Disclosure",
  "generate.step_validity": "Validity",
  "generate.step_result": "Result",
  "generate.org_name": "Name of the organisation",
  "generate.org_country": "Country (ISO 3166-1, two letters)",
  "generate.org_role": "Role",
  "generate.org_url": "Website",
  "generate.role_manufacturer": "Manufacturer",
  "generate.role_operator": "Operator",
  "generate.role_both": "Both",
  "generate.role_other": "Other",
  "generate.domain": "Your domain",
  "generate.domain_help": "Legacy 0.x only: the historical default was https://<your domain>/.well-known/cvd.json.",
  "generate.canonical": "Location of the file",
  "generate.posture_question": "How do you deal with security research?",
  "generate.statement": "In your own words",
  "generate.statement_help": "Shown to people, not evaluated by tools. Up to 1000 characters.",
  "generate.contact_question": "Where should reports go?",
  "generate.contact_equal_note":
    "These options rank equally. This site recommends no provider and pre-fills none.",
  "generate.channel_email": "Your own email address",
  "generate.channel_form": "Your own web form",
  "generate.channel_service": "A third-party intake service",
  "generate.channel_service_help": "Enter any URL. Nothing is suggested here.",
  "generate.channel_postal": "Postal address",
  "generate.channel_preferred": "preferred",
  "generate.languages": "Languages you accept reports in",
  "generate.pgp_url": "PGP key (URL)",
  "generate.pgp_fingerprint": "Fingerprint",
  "generate.ack_hours": "Acknowledge within (hours)",
  "generate.update_days": "Status update every (days)",
  "generate.scope_web": "Domains",
  "generate.scope_products": "Products",
  "generate.scope_pattern": "Host pattern",
  "generate.scope_pattern_help": "Example: example.com or *.example.com",
  "generate.scope_state": "State",
  "generate.scope_reason": "Reason for exclusion",
  "generate.scope_precedence": "Which entry wins on a conflict?",
  "generate.product_name": "Name",
  "generate.product_purl": "Package URL",
  "generate.product_versions": "Versions",
  "generate.product_supported": "Supported until",
  "generate.product_sbom": "SBOM (URL)",
  "generate.testing_default": "Everything not listed is",
  "generate.testing_activity": "Activity",
  "generate.testing_state": "State",
  "generate.testing_note": "Note",
  "generate.testing_rps": "Maximum requests per second",
  "generate.testing_ua": "User agent must contain",
  "generate.testing_targets": "Only against these targets (one per line)",
  "generate.testing_account": "Where to request a test account",
  "generate.testing_skip_note":
    "This step applies only to the postures open and limited. Your posture does not invite testing, so no rules are written.",
  "generate.report_fields": "A report must contain",
  "generate.report_proof": "Proof of exploitation",
  "generate.report_formats": "Accepted formats",
  "generate.report_max_mb": "Maximum attachment size (MB)",
  "generate.report_template": "Template (URL)",
  "generate.disclosure_model": "Disclosure model",
  "generate.disclosure_deadline": "Usual deadline (days)",
  "generate.disclosure_advisory": "Advisories (URL)",
  "generate.disclosure_credit": "Credit for reporters",
  "generate.credit_offered": "Offered",
  "generate.credit_on_request": "On request",
  "generate.credit_none": "None",
  "generate.expires": "Valid until",
  "generate.expires_help":
    "Twelve months is a sensible default: a file reviewed once a year is less likely to be out of date without anyone noticing.",
  "generate.expires_months": "Months from today",
  "generate.result_title": "Your files",
  "generate.result_step1": "Put the file here",
  "generate.result_step2": "Add this line to your security.txt",
  "generate.result_step2_help":
    "If the host has no security.txt yet, use the one above — it already carries this line.",
  "generate.result_step3": "Check it",
  "generate.result_securitytxt_preview": "Show the security.txt",
  "generate.import_title": "Already publish a security.txt?",
  "generate.import_help":
    "Drop the file in and whatever it already answers is filled in for you: the contacts, the languages, the expiry date, the domain, and the link to your key. The key itself is never touched — only the address pointing at it is carried over, unchanged. The file is read in this tab and never uploaded.",
  "generate.securitytxt_drop_hint": "Drop your security.txt here, or choose a file",
  "generate.import_done": "Read in",
  "generate.import_done_help":
    "At the last step you get this same file back with the CVD-Policy line added, so you can publish both together.",
  "generate.import_signed":
    "This file is signed. Adding the CVD-Policy line breaks that signature — there is no way to add a field and keep it — so you will have to sign the file again before publishing it.",
  "generate.import_forget": "Forget this file",
  "generate.merge_title": "Update a security.txt you already have",
  "generate.merge_help":
    "Paste or drop your current file. It comes back with the CVD-Policy field pointing at your cvd.json, and nothing else touched — comments, order and blank lines all stay. It is read in this tab and never uploaded.",
  "generate.merge_paste": "Your current security.txt",
  "generate.merge_added": "Field added",
  "generate.merge_replaced": "Field updated",
  "generate.merge_unchanged": "Already up to date",
  "generate.merge_previous": "was",
  "generate.merge_signed":
    "This file is signed. The signature no longer matches the changed text, so sign it again before publishing.",
  "generate.result_publish": "Publishing them",
  // One line per field, saying what goes in it. Kept short on purpose: this is
  // a hint next to an input, not the explanation the spec page carries.
  "generate.hint_org_name":
    "The legal name of the organisation this policy is for, as it appears on your imprint or register entry.",
  "generate.hint_domain":
    "The domain you will publish the file on. It fills in the file location and a first scope entry for you.",
  "generate.hint_canonical":
    "The exact address the finished cvd.json will answer at. Reporters and tools use it to confirm the file is really yours.",
  "generate.hint_org_country":
    "Two-letter country code for where the organisation is based.",
  "generate.hint_org_url":
    "Your main website, for a reporter checking who they are about to contact.",
  "generate.hint_channel_email":
    "An address a stranger can reach without an account. A role address outlives any one person.",
  "generate.hint_channel_form":
    "A page with a form for reports. It has to be reachable without logging in.",
  "generate.hint_channel_postal":
    "A postal address. It appears in the policy but has no security.txt field, so it is never written to that file.",
  "generate.hint_languages":
    "Languages you can handle a report in, most comfortable first.",
  "generate.hint_pgp_url":
    "Where your public key can be fetched, so a reporter can encrypt before sending.",
  "generate.hint_pgp_fingerprint":
    "The fingerprint of that key, so a reporter can check they fetched the right one.",
  "generate.hint_ack_hours":
    "Hours within which you will confirm a report arrived. Confirming receipt is not the same as having an answer.",
  "generate.hint_update_days":
    "How often you will send a progress update while the report is open, in days.",
  "generate.hint_expires":
    "The date this policy stops being valid. Set a reminder to renew it: an expired policy is treated as none at all.",
  "generate.hint_statement":
    "One or two sentences in your own words. It is shown to reporters as written and changes nothing a tool checks.",
  "generate.hint_scope_pattern":
    "A host or a wildcard covering the systems this entry is about.",
  "generate.hint_scope_reason":
    "Why this is out of scope. Written for the person reading it, not for a tool.",
  "generate.hint_product_name":
    "The product as you sell or ship it, the name a reporter would recognise.",
  "generate.hint_product_versions":
    "Which versions this covers. A range or a list, in whatever form your release notes use.",
  "generate.hint_product_supported":
    "The date support ends for these versions.",
  "generate.hint_product_purl":
    "The package URL, if the product is distributed through a package registry.",
  "generate.hint_product_sbom":
    "Where the software bill of materials for this product can be fetched.",
  "generate.hint_testing_activity":
    "The kind of testing this rule is about. Anything you do not list is treated as prohibited.",
  "generate.hint_testing_rps":
    "The most requests per second you are willing to absorb during testing.",
  "generate.hint_testing_ua":
    "A user agent you ask researchers to send, so you can tell their traffic from an attack.",
  "generate.hint_testing_targets":
    "Where testing should happen instead, when you would rather it stayed off production.",
  "generate.hint_testing_account":
    "Where a researcher gets a test account, if your rules require them to use one.",
  "generate.hint_testing_note":
    "Anything a researcher has to know that the rule itself does not say.",
  "generate.hint_report_max_mb":
    "The largest attachment your inbox will accept, in megabytes.",
  "generate.hint_report_template":
    "A template you would like reports to follow. A missing field must never stop someone reporting.",
  "generate.hint_intake_url":
    "The endpoint that accepts a structured report. https only, and never with credentials in the URL.",
  "generate.hint_intake_schema":
    "The schema that endpoint expects, so a tool can check a report before sending it.",
  "generate.hint_intake_max_bytes":
    "The largest submission the endpoint accepts, in bytes.",
  "generate.hint_disclosure_deadline":
    "Days after a report arrives before details may be published. Counted from receipt, not from a fix.",
  "generate.result_zip_help":
    "Everything in one archive, with both directories already laid out to unpack at your web root. Take this unless you need a single file on its own: the security.txt inside names /security/cvd.html in its Policy: field, so the two have to be published together.",
  "generate.result_files_help":
    "cvd.json and security.txt belong under /.well-known/, where a tool knows to look for them. cvd.html is the page for people and goes to /security/ instead: nothing discovers it, so it has no business in a reserved directory. Publish it too, or the Policy: line in security.txt leads nowhere.",
  "generate.result_files_merged":
    "The security.txt here is your own file with the CVD-Policy line put in, not a new one. cvd.html is the page for people, built from the same answers.",
  "generate.result_permalink": "Draft link",
  "generate.result_permalink_help":
    "The draft is encoded in the part of the URL after the #. Browsers never send that part to a server, so the link stays on your device unless you pass it on yourself.",
  "generate.result_no_leak": "No data left your browser. These files were built entirely on your device.",
  "generate.result_invalid": "The document is not valid yet. The validator says why.",
  "generate.result_valid": "The document is valid.",
  "generate.clear_state": "Delete entries from this browser",
  "generate.clear_state_help": "Your answers are held in this tab only and are gone when you close it.",
  "generate.unsaved_warning": "Your entries are not stored anywhere. Leaving this page discards them.",
  "generate.v1_title": "Generate a V1 CVD Policy",
  "generate.v1_lead": "Build every V1 field in the guided editor, or work directly with JSON, then prepare files for the exact locations you control.",
  "generate.v1_notice_intro": "Experimental implementation of",
  "generate.v1_notice_change": "The proposed field name and media type may change.",
  "generate.policy_uri": "Policy URI",
  "generate.policy_uri_help": "Required, explicit HTTPS URI. There is no standardized default JSON path.",
  "generate.security_txt_uri": "security.txt URI",
  "generate.human_policy_uri": "Human-readable Policy URI",
  "generate.human_policy_uri_help": "A fresh security.txt links this URI through its Policy field.",
  "generate.human_policy_merge_note": "When merging, existing Policy fields stay unchanged. The generator does not add or replace a Policy field for this HTML file.",
  "generate.v1_policy_json": "V1 policy JSON",
  "generate.merge_existing": "Merge into an existing security.txt",
  "generate.merge_existing_help": "Comments and existing fields are preserved. Every old CVD-Policy field is replaced by exactly one value. Clearsigned files are refused.",
  "generate.local_validation": "Local validation",
  "generate.valid_v1": "Locally valid V1 document",
  "generate.local_scope": "Local validation checks the document, not authority, deployment, ownership, legal authorization, or testing permission for a target.",
  "generate.download_layout": "Download exact web-root layout",
  "generate.zip_unavailable": "No ZIP: all three safe paths must share one HTTPS origin and contain no query, fragment, credentials, or parent segments.",
  "generate.network_check": "Network check after deployment",
  "generate.local_only": "This browser performs local document validation only. The CLI checks network discovery, authority, redirects, media type and the deployed policy because CORS may block browser requests.",
  "generate.security_txt_uri_error": "security.txt URI must be an exact HTTPS /.well-known/security.txt URL",
  "generate.editor_mode": "Editor mode",
  "generate.editor_guided": "Guided editor",
  "generate.editor_json": "Advanced JSON",
  "generate.editor_json_help": "Direct JSON editing preserves every V1 value. Apply a valid document to return to the guided editor.",
  "generate.editor_apply_json": "Apply JSON to guided editor",
  "generate.editor_identity": "Document and organisation",
  "generate.editor_identity_help": "The publisher and the two timestamps that bound this exact statement.",
  "generate.editor_org_name": "Organisation name",
  "generate.editor_org_uri": "Organisation website",
  "generate.editor_last_updated": "Last updated",
  "generate.editor_expires": "Expires",
  "generate.editor_set_now": "Set to now",
  "generate.editor_contact": "Report contact",
  "generate.editor_contact_help": "Ordered mailto, tel or HTTPS URIs. These are contact routes, not report transport defined by V1.",
  "generate.editor_channels": "Contact channels, one URI per line",
  "generate.editor_channels_help": "At least one. Order the channels by your preference.",
  "generate.editor_languages": "Preferred language tags, one per line",
  "generate.editor_encryption": "Encryption URIs, one per line",
  "generate.editor_research": "Research posture",
  "generate.editor_research_help": "Posture is context. Even open does not permit testing without an explicit permitted rule.",
  "generate.editor_posture": "Posture",
  "generate.editor_posture_open": "Open to research",
  "generate.editor_posture_limited": "Limited research",
  "generate.editor_posture_report_only": "Reports only",
  "generate.editor_posture_prohibited": "Research prohibited",
  "generate.editor_statement": "Publisher statement",
  "generate.editor_scope": "Reporting scope",
  "generate.editor_scope_help": "Assets described here are reportable. Scope does not prove ownership or grant testing permission.",
  "generate.editor_web_scope": "Web targets",
  "generate.editor_add_web": "Add web target",
  "generate.editor_web_entry": "Web target {n}",
  "generate.editor_product_scope": "Products",
  "generate.editor_add_product": "Add product",
  "generate.editor_product_entry": "Product {n}",
  "generate.editor_id": "Stable ID",
  "generate.editor_state": "Scope state",
  "generate.editor_rule_state": "Rule state",
  "generate.editor_in": "Reportable (in)",
  "generate.editor_out": "Excluded (out)",
  "generate.editor_host": "Host",
  "generate.editor_path": "Path prefix",
  "generate.editor_ports": "Ports, comma-separated",
  "generate.editor_subdomains": "Include subdomains",
  "generate.editor_product_name": "Product name",
  "generate.editor_identifiers": "Product identifier URIs, one per line",
  "generate.editor_testing": "Testing rules",
  "generate.editor_testing_help": "Rules are publisher statements without independent legal effect. Prohibitions override permissions.",
  "generate.editor_testing_enable": "Include explicit testing rules",
  "generate.editor_testing_notice": "Permitted rules need target IDs. Automated scanning and fuzzing also need rate and concurrency limits; credential testing additionally requires test accounts only.",
  "generate.editor_add_rule": "Add rule",
  "generate.editor_rule": "Testing rule {n}",
  "generate.editor_activity": "Activity or extension URI",
  "generate.editor_activity_custom": "Custom extension activity",
  "generate.editor_activity_uri": "Custom activity URI",
  "generate.editor_prohibited": "Prohibited",
  "generate.editor_permitted": "Publisher-stated permitted",
  "generate.editor_permitted_unavailable": "Permitted rules require an open or limited posture and at least one reportable web target.",
  "generate.editor_target_ids": "Target IDs, one per line",
  "generate.editor_no_testing_targets": "Add a reportable web target before permitting a testing activity.",
  "generate.editor_conditions": "Add conditions",
  "generate.editor_rps": "Maximum requests per second",
  "generate.editor_concurrency": "Maximum concurrent requests",
  "generate.editor_user_agent": "Required user-agent token",
  "generate.editor_test_accounts": "Test accounts only",
  "generate.editor_reporting": "Reporting preferences",
  "generate.editor_reporting_help": "Requested fields are preferences, not submission requirements. V1 defines no intake endpoint, API or report transport.",
  "generate.editor_requested_fields": "Requested report fields",
  "generate.editor_requested_affected_asset": "Affected asset",
  "generate.editor_requested_vulnerability_type": "Vulnerability type",
  "generate.editor_requested_description": "Description",
  "generate.editor_requested_reproduction_steps": "Reproduction steps",
  "generate.editor_requested_impact": "Impact",
  "generate.editor_requested_environment": "Environment",
  "generate.editor_requested_evidence": "Evidence",
  "generate.editor_requested_researcher_contact": "Researcher contact",
  "generate.editor_requested_disclosure_preference": "Disclosure preference",
  "generate.editor_proof": "Proof of exploitation",
  "generate.editor_proof_not_requested": "Not requested",
  "generate.editor_proof_requested": "Requested if safe",
  "generate.editor_proof_prohibited": "Prohibited",
  "generate.editor_response": "Response targets",
  "generate.editor_response_help": "Optional operational targets, not promises or guarantees.",
  "generate.editor_response_enable": "State response targets",
  "generate.editor_ack_days": "Acknowledgement within days",
  "generate.editor_assessment_days": "Initial assessment within days",
  "generate.editor_update_days": "Update interval in days",
  "generate.editor_disclosure": "Disclosure preference",
  "generate.editor_disclosure_help": "A preference for coordination, not permission to publish.",
  "generate.editor_disclosure_enable": "State a disclosure preference",
  "generate.editor_approach": "Approach",
  "generate.editor_approach_coordinated": "Coordinated",
  "generate.editor_approach_case": "Case by case",
  "generate.editor_approach_none": "No preference",
  "generate.editor_default_days": "Default period in days",
  "generate.editor_disclosure_statement": "Disclosure statement",
  "generate.editor_extensions": "Extensions",
  "generate.editor_extensions_help": "Optional URI-keyed data. Mark an extension critical only when consumers must understand it before using the policy.",
  "generate.editor_critical_extensions": "Critical extension URIs, one per line",
  "generate.editor_extension": "Extension {n}",
  "generate.editor_extension_uri": "Extension URI",
  "generate.editor_extension_value": "JSON value",
  "generate.editor_extension_critical": "This extension is critical",
  "generate.editor_extension_error": "Extension URIs must be unique and every value must be valid JSON. Publication files stay disabled until this is fixed.",
  "generate.editor_invalid": "Resolve the errors in the guided editor before downloading publication files.",
  "generate.editor_add_extension": "Add extension",

  "validate.title": "Validate a policy",
  "validate.lead": "Paste a file, drop it in, or load an example. Nothing is uploaded.",
  "validate.paste": "Paste",
  "validate.examples": "Examples",
  "validate.drop_hint": "Drop a policy JSON here, or choose a file",
  "validate.result_valid": "Valid",
  "validate.result_valid_local_v1": "Locally valid V1 document",
  "validate.result_invalid": "Invalid",
  "validate.count_errors_one": "{n} error",
  "validate.count_errors_other": "{n} errors",
  "validate.count_warnings_one": "{n} warning",
  "validate.count_warnings_other": "{n} warnings",
  "validate.count_notes_one": "{n} note",
  "validate.count_notes_other": "{n} notes",
  "validate.errors": "Errors",
  "validate.warnings": "Warnings",
  "validate.infos": "Notes",
  "validate.no_issues": "No objections. The document follows the specification.",
  "validate.fix_in_generator": "Open in the generator",
  "validate.explain_this": "Show in plain language",
  "validate.url_title": "Checking a URL",
  "validate.url_body":
    "A browser cannot fetch another domain's file without that domain allowing it, and routing the request through a server here would mean a server that sees which policies you check. It would also be a backend, which this site does not have. Use the command below instead.",
  "validate.v1_title": "Validate a CVD Policy",
  "validate.v1_lead": "Paste or upload JSON. Validation runs locally in your browser.",
  "validate.v1_notice": "V1 is an experimental implementation of",
  "validate.legacy_title": "Legacy 0.x validation",
  "validate.legacy_body": "Opt in only for existing 0.1/0.2 documents.",
  "validate.policy_json": "Policy JSON",
  "validate.v1_no_issues": "No issues found.",
  "validate.local_scope": "This result does not establish authority, deployment correctness, ownership, legal authorization, or testing permission for a target.",
  "validate.deployed_title": "Check a deployed policy",
  "validate.deployed_help": "The CLI follows /.well-known/security.txt to its announced CVD-Policy URI. The browser validator does not perform network discovery.",

  "explain.page_subtitle": "Coordinated vulnerability disclosure policy",
  "explain.page_expires": "This policy is stated until",
  "explain.title": "Explain a Legacy 0.x policy",
  "explain.lead": "A frozen 0.1 or 0.2 document, written out for someone who does not read JSON.",
  "explain.legacy_notice": "This explainer does not support V1. Use Validate for a local V1 document check.",
  "explain.paste_hint": "Paste a document, drop a file, or load an example.",
  "explain.show_raw": "Show raw data",
  "explain.hide_raw": "Hide raw data",
  "explain.open_in_validator": "Open in the validator",
  "explain.no_rating": "No score, no maturity level, no comparison with other organisations. On purpose.",
  "explain.organization": "Organisation",
  "explain.country": "Country",
  "explain.valid_until": "Valid until",
  "explain.updated": "Last changed",
  "explain.posture": "Security research",
  "explain.statement": "In their words",
  "explain.in_scope_domains": "Domains in scope",
  "explain.in_scope_products": "Products in scope",
  "explain.out_of_scope": "Excluded systems",
  "explain.precedence": "On a conflict",
  "explain.report_to": "Report to",
  "explain.encryption": "Encryption",
  "explain.languages": "Languages",
  "explain.response_within": "Response within",
  "explain.testing_default": "Anything not listed",
  "explain.required_fields": "A report must contain",
  "explain.proof_of_exploitation": "Proof of exploitation",
  "explain.model": "Disclosure",
  "explain.deadline": "Usual deadline",
  "explain.advisories": "Advisories",
  "explain.pgp_available": "PGP available",
  "explain.none": "not stated",
  "explain.hours_one": "{n} hour",
  "explain.hours_other": "{n} hours",
  "explain.days_one": "{n} day",
  "explain.days_other": "{n} days",
  "explain.section.header": "Document",
  "explain.section.research": "Security research",
  "explain.section.scope": "Scope",
  "explain.section.contact": "Contact",
  "explain.section.testing": "Testing rules",
  "explain.section.report_requirements": "Report requirements",
  "explain.section.disclosure": "Disclosure",

  "posture.open.headline": "TESTING WELCOME — within the rules below",
  "posture.open.body":
    "Testing the listed systems is welcome, within the rules you define below. Choose this only if you can act on the reports that arrive.",
  "posture.limited.headline": "LIMITED TESTING — in a defined frame only",
  "posture.limited.body":
    "Testing is permitted only in a clearly drawn frame, such as against a sandbox or with your own test account. Everything else is not permitted.",
  "posture.report_only.headline": "NO INVITATION TO TEST — reports welcome",
  "posture.report_only.body":
    "You do not invite testing, but you accept reports and act on them. That is not a weaker statement than a testing permission — it is an honest one. Most organisations say nothing at all today. This says something.",
  "posture.prohibited.headline": "TESTING RULED OUT",
  "posture.prohibited.body":
    "Testing is ruled out, and reports are either unwanted or go through another route. That is a useful statement too — a researcher then knows not to start here.",
  "posture.recommended": "right for most organisations",

  "precedence.out_overrides_in": "an exclusion wins",
  "precedence.explicit_order": "the last matching entry wins",

  // Bare adjectives: the label supplies the verb ("Everything not listed is"),
  // as it already does in German. With "is allowed" here the select read
  // "Everything not listed is → is prohibited".
  "testing.default.allowed": "allowed",
  "testing.default.prohibited": "prohibited",
  "testing.state.allowed": "allowed",
  "testing.state.prohibited": "prohibited",

  "activity.manual_testing": "Manual testing",
  "activity.automated_scanning": "Automated scanning",
  "activity.fuzzing": "Fuzzing",
  "activity.credential_testing": "Credential testing",
  "activity.brute_force": "Brute forcing",
  "activity.dos": "Denial of service",
  "activity.social_engineering": "Social engineering",
  "activity.phishing": "Phishing",
  "activity.physical": "Physical access",
  "activity.spam": "Spam",
  "activity.data_exfiltration": "Exfiltrating data",
  "activity.account_takeover": "Taking over accounts",
  "activity.third_party_pivot": "Pivoting to third parties",
  "activity.supply_chain": "Supply chain",
  "activity.persistence": "Persistence",

  "field.affected_asset": "affected system",
  "field.description": "description",
  "field.reproduction_steps": "steps to reproduce",
  "field.impact": "impact",
  "field.discovery_date": "date of discovery",
  "field.reporter_contact": "your contact details",
  "field.proposed_fix": "proposed fix",

  "proof.required": "required",
  "proof.optional": "optional",
  "proof.prohibited": "not wanted",

  "disclosure.coordinated": "coordinated",
  "disclosure.full_after_deadline": "full disclosure after the deadline",
  "disclosure.vendor_only": "vendor only",
  "disclosure.no_disclosure": "no disclosure",

  "scope.state.in": "in scope",
  "scope.state.out": "excluded",
  "scope.reason.third_party": "operated by a third party",
  "scope.reason.legacy": "legacy system",
  "scope.reason.not_operated": "not operated by us",
  "scope.reason.other": "other",

  "issue.required_missing": "The field {field} is missing.",
  "issue.required_missing.hint": "It is required; without it the document cannot be evaluated.",
  "issue.testing_required": "This posture invites testing, so testing rules are required.",
  "issue.testing_required.hint": "Add a testing section, or choose report_only.",
  "issue.version_unsupported": "Unknown version. Expected {expected}.",
  "issue.version_unsupported.hint": "Consumers must not guess at an unknown version.",
  "issue.enum_invalid": "This value is not defined.",
  "issue.enum_invalid.hint": "Allowed: {allowed}",
  "issue.posture_unknown": "This posture is not defined.",
  "issue.posture_unknown.hint": "Allowed: open, limited, report_only, prohibited.",
  "issue.canonical_not_https": "canonical must be an absolute https URL.",
  "issue.canonical_not_https.hint": "Legacy 0.x example: https://example.com/.well-known/cvd.json",
  "issue.pattern_invalid": "This value does not have the expected shape.",
  "issue.format_invalid": "This value is not a valid {format}.",
  "issue.type_invalid": "Expected {expected} here.",
  "issue.max_items": "Too many entries here.",
  "issue.min_items": "At least one entry is required here.",
  "issue.schema_invalid": "This value breaks the rule {keyword}.",
  "issue.json_parse": "This is not valid JSON. {detail}",
  "issue.expires_past": "The expiry date is in the past ({expires}).",
  "issue.expires_past.hint": "Consumers treat this document as if it were not there.",
  "issue.expires_far": "The expiry date is more than twelve months away ({expires}).",
  "issue.expires_far.hint": "A shorter period makes it more likely someone looks at the file again.",
  "issue.canonical_mismatch": "canonical points at {canonical}, but the file was fetched from {retrieved}.",
  "issue.canonical_mismatch.hint": "That may mean the document was copied from somewhere else.",
  "issue.scope_foreign_host": "{pattern} is not at or under {own}, where this document is published.",
  "issue.scope_foreign_host.hint": "A document speaks for the host it sits on and everything below it. Publish one at that host too, or let it point at this document from its own security.txt.",
  "issue.testing_target_foreign": "The rule for {activity} names {target}, which {own} does not cover.",
  "issue.testing_target_foreign.hint": "Tools will ignore this target unless that host points at this document itself.",
  "issue.canonical_has_credentials": "canonical contains a username or password.",
  "issue.canonical_has_credentials.hint": "This file is published. Remove the credentials and treat them as compromised.",
  "issue.scope_pattern_unusable": "{pattern} does not name a host, so it matches nothing.",
  "issue.scope_pattern_unusable.hint": "Write a hostname such as example.com, or *.example.com for everything under it.",
  "issue.posture_contradiction": "The posture {posture} does not invite testing, but testing rules are listed.",
  "issue.posture_contradiction.hint": "Remove the rules, or choose the posture limited or open if you do mean to allow testing.",
  "issue.testing_ignored": "Testing rules are ignored for the posture {posture}.",
  "issue.testing_ignored.hint": "Set the default to prohibited, or choose a posture that invites testing.",
  "issue.testing_default_broad": "Everything not listed is allowed, and nothing is ruled out.",
  "issue.testing_default_broad.hint": "This permits denial of service, social engineering and physical access too. Rule out what you do not want.",
  "issue.condition_targets_empty": "The rule for {activity} has an empty target list.",
  "issue.condition_targets_empty.hint": "An empty list places no restriction at all. Remove it, or name the targets.",
  "issue.string_too_long": "This text is longer than {limit} characters.",
  "issue.string_empty": "This value must not be empty.",
  "issue.number_too_small": "This number is too small (limit {limit}).",
  "issue.number_too_large": "This number is too large (limit {limit}).",
  "issue.scope_private_address": "{pattern} is a private or loopback address.",
  "issue.scope_private_address.hint": "Outside readers cannot reach it, and naming internal addresses in a public file reveals more than it achieves.",
  "generate.step_intake": "Machine-readable intake",
  "generate.intake_question": "Can you receive structured reports?",
  "generate.intake_note": "Optional. A document without this is complete — the contact channels above stay the way people report.",
  "generate.intake_url": "Endpoint that accepts reports",
  "generate.intake_url_help": "Any https URL, yours or a provider's. Nothing is suggested here.",
  "generate.intake_schema": "Schema the endpoint accepts (URL)",
  "generate.intake_profile": "Report profile",
  "generate.intake_anonymous": "Reports without contact details are accepted",
  "generate.intake_max_bytes": "Largest accepted submission (bytes)",
  "generate.intake_attachments": "Attachments",
  "generate.intake_attachments_accepted": "accepted",
  "generate.intake_attachments_after_contact": "after contact",
  "generate.intake_attachments_not_accepted": "not accepted",
  "explain.structured_intake": "Structured submission",
  "explain.intake_offered": "possible",
  "explain.anonymous_reports": "Anonymous reports",
  "common.yes": "yes",
  "common.no": "no",
  "issue.intake_not_https": "The intake endpoint must be an absolute https URL.",
  "issue.intake_not_https.hint": "Reports carry the details of an unfixed vulnerability. They must not travel unencrypted.",
  "issue.intake_has_credentials": "The intake endpoint contains a username or password.",
  "issue.intake_has_credentials.hint": "This file is published. Remove the credentials and treat them as compromised.",
  "issue.intake_third_party": "Reports go to {host}, which is outside {own}.",
  "issue.intake_third_party.hint": "That is normal when a provider runs your intake. Make sure it is the one you chose.",
  "issue.intake_needs_version": "This document uses intake but declares an older version.",
  "issue.intake_needs_version.hint": "Set cvd_policy to {expected} so tools know to read it.",
  "issue.intake_profile_without_schema": "Profile {profile} is named, but no schema URL is given.",
  "issue.intake_profile_without_schema.hint": "Without a schema URL a tool has to assume the profile's defaults.",
  "issue.report_no_reproduction": "No steps to reproduce.",
  "issue.report_no_impact": "No impact given.",
  "issue.report_no_exploitation": "No statement whether this is being exploited.",
  "issue.report_credit_without_name": "Public credit was asked for, but no name was given.",
  "issue.report_share_without_contact": "Sharing contact details was allowed, but none were given.",
  "issue.scope_empty": "The scope lists neither domains nor products.",
  "issue.scope_empty.hint": "A target that nothing matches counts as out of scope.",
  "issue.scope_overlap": "{pattern} overlaps with the earlier entry {other}.",
  "issue.scope_overlap.hint": "Check which entry you want to win, given your precedence setting.",
  "issue.product_support_past": "Support for {name} ended on {date}.",
  "issue.testing_rule_duplicate": "A second rule for {activity} — only the first one applies.",
  "issue.testing_rule_duplicate.hint": "Merge the rules into one. A later, less restrictive duplicate has no effect and misleads anyone reading the file.",
  "issue.testing_unreachable": "The rule for {activity} allows testing, but {target} is out of scope.",
  "issue.testing_unreachable.hint": "The rule can never take effect as written.",
  "issue.contact_missing_encryption": "An open posture without a way to send encrypted reports.",
  "issue.contact_missing_encryption.hint": "Consider publishing a PGP key or an S/MIME certificate.",

  "tools.schema_frozen": "0.1 and 0.2 are frozen legacy formats; V1 may change",
  "tools.report_profile": "Report profile",
  "tools.report_profile_note": "legacy 0.x only; V1 defines no report transport",
  "tools.title": "Tools",
  "tools.lead": "Everything needed to implement the format, and everything needed to use the format without this site.",
  "tools.for_implementers": "For implementers",
  "tools.schema": "JSON Schema",
  "tools.library": "Library",
  "tools.cli": "Command line",
  "tools.on_npm": "on npm",
  "tools.examples": "V1 examples",
  "tools.legacy_examples": "Legacy 0.x examples",
  "tools.legacy_report_profile": "Legacy report profile",
  "tools.corpus": "Test corpus",
  "tools.action": "GitHub Action",
  "tools.cli_body": "Exit codes: 0 full V1 success, 1 validation error, 2 explicit application/json compatibility warning, 3 not reachable. application/json is accepted only with --allow-application-json.",
  "tools.securitytxt": "security.txt",
  "tools.securitytxt_body":
    "The V1 library creates a complete security.txt or returns a merged string that preserves comments, field order, blank lines, line endings and every field except prior CVD-Policy entries.",
  "tools.securitytxt_signed":
    "Merging a clear-signed file throws instead of silently breaking its signature. Create the unsigned result separately and sign it again.",
  "tools.third_party": "Third-party implementations",
  "tools.third_party_empty": "This list is open. Pull requests welcome.",
  "tools.v1_notice_intro": "Experimental implementation of",
  "tools.v1_notice_release": "Install the exact release candidate, not the floating next tag.",

  "faq.title": "Questions",
  "faq.q_prohibit": "What if I want to rule out testing?",
  "faq.a_prohibit":
    "Then say so, with posture prohibited or report_only. That is a supported answer, not a failure. A researcher who reads it knows where not to start, and you get reports through the channel you chose instead of through a stranger's blog post.",
  "faq.q_securitytxt": "Does this replace security.txt?",
  "faq.a_securitytxt":
    "No. security.txt stays where it is and keeps doing its job. This format adds one field to it, CVD-Policy, pointing at a file that answers the questions security.txt has no fields for.",
  "faq.q_securitytxt_write": "Can it write my security.txt as well?",
  "faq.a_securitytxt_write":
    "Yes. If you have none, the V1 generator writes Contact, Expires, Canonical, Policy and exactly one CVD-Policy field pointing at the explicit HTTPS policy URI you chose. If you already have one, it preserves comments and every existing field, removes all old CVD-Policy fields and inserts the configured value once. It is read in your browser and never uploaded.",
  "faq.q_signed": "I sign my security.txt. What happens?",
  "faq.a_signed":
    "RFC 9116 allows a clear-signed security.txt, and any change breaks its signature. The generator therefore refuses to modify a signed file and produces no changed result. Prepare an unsigned replacement, add CVD-Policy, then sign that complete file again before publishing it.",
  "faq.q_cra": "Is this proof of CRA conformity?",
  "faq.a_cra":
    "No. The Cyber Resilience Act asks for processes, not for a JSON file. What this format can do is record parts of what you already decided — contact point, supported versions, disclosure practice — in a form an auditor can read and a tool can check. That is documentation, not conformity.",
  "faq.q_legal": "Does this give me legal certainty?",
  "faq.a_legal":
    "No. A policy document is a unilateral statement. It is not a contract, not consent in the criminal-law sense, and not a waiver of liability. Anyone relying on it does so at their own risk, and the same applies in reverse: publishing one gives you no claim against a researcher. If the legal position matters to your decision, ask a lawyer, not a file format.",
  "faq.q_machine": "Can incoming reports be processed automatically?",
  "faq.a_machine": "V1 describes which report fields are requested, but deliberately does not publish a report API or transport endpoint. Send reports only through a public Contact channel chosen by the publisher.",
  "faq.q_versions": "What happens to existing 0.1 and 0.2 documents?",
  "faq.a_versions": "They remain valid legacy formats and are not silently converted. This generator writes the incompatible V1 draft format; use legacy validation explicitly for existing documents.",
  "faq.q_who": "Who runs this site, and on what money?",
  "faq.a_who":
    "Skalvar Technologies UG (haftungsbeschränkt) in Wismar, Germany, runs it. The company earns its money developing IT security software — products you can buy from us and do not need in order to use this format. V1 defines no intake API or provider selection; publishers choose their own public Contact URI. If that ever changes, this site has stopped being neutral and you should say so publicly.",
  "faq.q_others": "Why not disclose.io, Bugcrowd or a bug bounty platform?",
  "faq.a_others":
    "Those solve a different problem well: running a programme, paying researchers, handling reports in volume. They assume you want a programme. Most organisations do not, and have nothing machine-readable to say instead. This format is the smaller layer underneath: a statement published at the URI you choose, readable without an account.",
  "faq.q_official": "Is this official or standardised?",
  "faq.a_official":
    "No. V1 is an experimental implementation of draft-behring-cvd-policy-00. The proposed security.txt field and media type are not registered and may change; 0.1 and 0.2 remain published legacy formats.",
  "faq.q_without": "Can I use this without you?",
  "faq.a_without":
    "Yes, and that is the point. The specification and schema are CC0: copy them, host them, change them. The library and this site are Apache-2.0. Every generated document works without a provider and may be published at any explicit HTTPS URI you control. Nothing here reports back to us.",
  "faq.q_data": "What happens to the data I type in?",
  "faq.a_data":
    "It stays in the current page. The V1 generator does not persist your policy, so reloading or leaving the page discards it. There is no server to send anything to.",

  "imprint.title": "Legal notice and privacy",
  "imprint.tmg": "Details pursuant to § 5 TMG",
  "imprint.represented_by": "Represented by",
  "imprint.managing_directors": "Managing directors",
  "imprint.register": "Commercial register",
  "imprint.register_court": "Registering court",
  "imprint.register_number": "Registration number",
  "imprint.vat_title": "VAT identification number",
  "imprint.vat_body": "VAT identification number pursuant to § 27 a UStG",
  "imprint.rstv": "Responsible for the content pursuant to § 18 (2) MStV",
  "imprint.email": "Email",
  "imprint.phone": "Phone",
  "imprint.contact": "Contact",
  "imprint.contact_note": "Given as plain text on purpose. There is no contact form on this site.",
  "imprint.privacy_title": "Privacy",
  "imprint.privacy_body":
    "This site sets no cookies, loads no external resources and runs no analytics. Files entered into the generator, validator or explainer are processed in your browser and are not transmitted. The V1 generator does not persist policy data; only the chosen language is kept in local storage and can be cleared in the browser.",
  "imprint.hosting_title": "Hosting",
  "imprint.hosting_body":
    "Static hosting in the EU. Server log files may record the usual request data for the purpose of operating and securing the site.",
  "imprint.funding_title": "Funding",
  "imprint.licence_title": "Licences",
} as const;

export type Dict = Record<keyof typeof en, string>;
