/** English is the source language; every other dictionary mirrors these keys. */
export const en = {
  "lang.switch": "Language",

  "nav.home": "Home",
  "nav.spec": "Specification",
  "nav.generate": "Generate",
  "nav.validate": "Validate",
  "nav.explain": "Explain",
  "nav.tools": "Tools",
  "nav.faq": "FAQ",
  "nav.imprint": "Legal notice",
  "nav.skip": "Skip to content",

  "common.copy": "Copy",
  "common.copied": "Copied",
  "common.download": "Download",
  "common.back": "Back",
  "common.next": "Next",
  "common.optional": "optional",
  "common.add": "Add",
  "common.remove": "Remove",
  "common.print": "Print",
  "common.of": "of",

  "footer.funding":
    "This site is run by Skalvar Technologies UG (haftungsbeschränkt) in Wismar, Germany, which earns its money developing IT security software. The format, the library and this site work without our products and without us.",
  "footer.privacy":
    "No tracking, no cookies, no analytics, no external fonts. Everything you type stays in your browser.",
  "footer.licence": "Specification and schema: CC0-1.0. Library and site: Apache-2.0.",

  "home.title": "State how you handle vulnerability reports.",
  "home.lead": "The CVD Policy Format is a small JSON file at a known location. It says whether security research is welcome, on what, under which conditions, and how to report. Where an organisation can process reports automatically, it also says where a structured report may be sent. Machines can read it. So can people.",
  "home.what_title": "In sixty seconds",
  "home.what_body": "security.txt names a contact. It cannot say whether testing is allowed, which systems are yours, or what happens after a report arrives. Today that answer is prose on a web page, if it exists at all. This format puts it in one file that a tool can check before it sends a single request — and, since version 0.2, lets you state where a structured report goes, so incoming reports need not be parsed out of an email.",
  "home.privacy_title": "Nothing leaves your device",
  "home.privacy_body":
    "The generator, the validator and the explainer run entirely in your browser. There is no backend, no upload and no request to any other domain. Open your network tab and check.",
  "home.cta_generate": "Create a file",
  "home.cta_validate": "Check a file",
  "home.cta_spec": "Read the specification",
  "home.example_title": "What it looks like",
  "home.example_caption": "A complete document for an organisation that accepts reports but does not invite testing.",
  "home.steps_title": "Three steps",
  "home.step_1": "Answer a handful of questions and download cvd.json.",
  "home.step_2": "Put the file at /.well-known/cvd.json on your domain.",
  "home.step_3": "Add one line to your security.txt.",
  "home.not_title": "What this is not",
  "home.not_1": "Not a replacement for security.txt — it adds one field to it.",
  "home.not_2": "Not proof of regulatory conformity, including under the CRA.",
  "home.not_3": "Not legal protection. It records a statement, nothing more.",
  "home.not_4": "Not a rating. No score, no maturity level, no comparison.",

  "spec.title": "Specification",
  "spec.lead": "Version 0.2, draft. Licensed CC0-1.0, so anyone can copy, quote and implement it.",
  "spec.translated_notice": "This translation is provided for convenience. The English text governs.",
  "spec.versions_note": "Version 0.1 stays published and valid: a released version never changes. 0.2 adds one optional field.",
  "spec.package_versions_note":
    "Package versions are not format versions. @cvd-policy/core 0.3 implements format 0.2: a package version says what changed in the package, while cvd_policy inside a document says which rules that document was written for.",
  "spec.schema": "JSON Schema",

  "notfound.title": "Page not found",
  "notfound.lead":
    "That address does not match any page here. The file you were looking for may live on someone else’s domain — this site only hosts the format itself.",

  "generate.title": "Generate a policy",
  "generate.lead": "What should reporters know about dealing with your organisation?",
  "generate.mode_quick": "Quick",
  "generate.mode_quick_help": "Five questions, a valid document in under two minutes.",
  "generate.mode_full": "Complete",
  "generate.mode_full_help": "Every field the format defines.",
  "generate.preview": "Live preview",
  "generate.preview_note": "Built in your browser as you type.",
  "generate.step_org": "Organisation",
  "generate.step_posture": "Posture",
  "generate.step_contact": "Contact",
  "generate.step_scope": "Scope",
  "generate.step_testing": "Testing rules",
  "generate.step_report": "Report requirements",
  "generate.step_disclosure": "Disclosure",
  "generate.step_validity": "Validity",
  "generate.step_result": "Result",
  "generate.org_name": "Name of the organisation",
  "generate.org_country": "Country (ISO 3166-1, two letters)",
  "generate.org_role": "Role",
  "generate.org_url": "Website",
  "generate.role_manufacturer": "Manufacturer",
  "generate.role_operator": "Operator",
  "generate.role_both": "Both",
  "generate.role_other": "Other",
  "generate.domain": "Your domain",
  "generate.domain_help": "The file belongs at https://<your domain>/.well-known/cvd.json.",
  "generate.canonical": "Location of the file",
  "generate.posture_question": "How do you deal with security research?",
  "generate.statement": "In your own words",
  "generate.statement_help": "Shown to people, not evaluated by tools. Up to 1000 characters.",
  "generate.contact_question": "Where should reports go?",
  "generate.contact_equal_note":
    "These options rank equally. This site recommends no provider and pre-fills none.",
  "generate.channel_email": "Your own email address",
  "generate.channel_form": "Your own web form",
  "generate.channel_service": "A third-party intake service",
  "generate.channel_service_help": "Enter any URL. Nothing is suggested here.",
  "generate.channel_postal": "Postal address",
  "generate.channel_preferred": "preferred",
  "generate.languages": "Languages you accept reports in",
  "generate.pgp_url": "PGP key (URL)",
  "generate.pgp_fingerprint": "Fingerprint",
  "generate.ack_hours": "Acknowledge within (hours)",
  "generate.update_days": "Status update every (days)",
  "generate.scope_web": "Domains",
  "generate.scope_products": "Products",
  "generate.scope_pattern": "Host pattern",
  "generate.scope_pattern_help": "Example: example.com or *.example.com",
  "generate.scope_state": "State",
  "generate.scope_reason": "Reason for exclusion",
  "generate.scope_precedence": "Which entry wins on a conflict?",
  "generate.product_name": "Name",
  "generate.product_purl": "Package URL",
  "generate.product_versions": "Versions",
  "generate.product_supported": "Supported until",
  "generate.product_sbom": "SBOM (URL)",
  "generate.testing_default": "Everything not listed is",
  "generate.testing_activity": "Activity",
  "generate.testing_state": "State",
  "generate.testing_note": "Note",
  "generate.testing_rps": "Maximum requests per second",
  "generate.testing_ua": "User agent must contain",
  "generate.testing_targets": "Only against these targets (one per line)",
  "generate.testing_account": "Where to request a test account",
  "generate.testing_skip_note":
    "This step applies only to the postures open and limited. Your posture does not invite testing, so no rules are written.",
  "generate.report_fields": "A report must contain",
  "generate.report_proof": "Proof of exploitation",
  "generate.report_formats": "Accepted formats",
  "generate.report_max_mb": "Maximum attachment size (MB)",
  "generate.report_template": "Template (URL)",
  "generate.disclosure_model": "Disclosure model",
  "generate.disclosure_deadline": "Usual deadline (days)",
  "generate.disclosure_advisory": "Advisories (URL)",
  "generate.disclosure_credit": "Credit for reporters",
  "generate.credit_offered": "Offered",
  "generate.credit_on_request": "On request",
  "generate.credit_none": "None",
  "generate.expires": "Valid until",
  "generate.expires_help":
    "Twelve months is a sensible default: a file reviewed once a year is less likely to be out of date without anyone noticing.",
  "generate.expires_months": "Months from today",
  "generate.result_title": "Your files",
  "generate.result_step1": "Put the file here",
  "generate.result_step2": "Add this line to your security.txt",
  "generate.result_step2_help":
    "If the host has no security.txt yet, use the one above — it already carries this line.",
  "generate.result_step3": "Check it",
  "generate.result_securitytxt_preview": "Show the security.txt",
  "generate.import_title": "Already publish a security.txt?",
  "generate.import_help":
    "Drop the file in and whatever it already answers is filled in for you: the contacts, the languages, the expiry date, the domain, and the link to your key. The key itself is never touched — only the address pointing at it is carried over, unchanged. The file is read in this tab and never uploaded.",
  "generate.securitytxt_drop_hint": "Drop your security.txt here, or choose a file",
  "generate.import_done": "Read in",
  "generate.import_done_help":
    "At the last step you get this same file back with the CVD-Policy line added, so you can publish both together.",
  "generate.import_signed":
    "This file is signed. Adding the CVD-Policy line breaks that signature — there is no way to add a field and keep it — so you will have to sign the file again before publishing it.",
  "generate.import_forget": "Forget this file",
  "generate.merge_title": "Update a security.txt you already have",
  "generate.merge_help":
    "Paste or drop your current file. It comes back with the CVD-Policy field pointing at your cvd.json, and nothing else touched — comments, order and blank lines all stay. It is read in this tab and never uploaded.",
  "generate.merge_paste": "Your current security.txt",
  "generate.merge_added": "Field added",
  "generate.merge_replaced": "Field updated",
  "generate.merge_unchanged": "Already up to date",
  "generate.merge_previous": "was",
  "generate.merge_signed":
    "This file is signed. The signature no longer matches the changed text, so sign it again before publishing.",
  "generate.result_publish": "Publishing them",
  "generate.result_files_help":
    "cvd.json is the machine-readable file. security.txt is what points reporters at it. cvd-policy.html is the page for people — the Policy: field in security.txt expects one, and it is built from the same answers.",
  "generate.result_files_merged":
    "The security.txt here is your own file with the CVD-Policy line put in, not a new one. cvd-policy.html is the page for people, built from the same answers.",
  "generate.result_permalink": "Draft link",
  "generate.result_permalink_help":
    "The draft is encoded in the part of the URL after the #. Browsers never send that part to a server, so the link stays on your device unless you pass it on yourself.",
  "generate.result_no_leak": "No data left your browser. These files were built entirely on your device.",
  "generate.result_invalid": "The document is not valid yet. The validator says why.",
  "generate.result_valid": "The document is valid.",
  "generate.clear_state": "Delete entries from this browser",
  "generate.clear_state_help": "Your answers are held in this tab only and are gone when you close it.",
  "generate.unsaved_warning": "Your entries are not stored anywhere. Leaving this page discards them.",

  "validate.title": "Validate a policy",
  "validate.lead": "Paste a file, drop it in, or load an example. Nothing is uploaded.",
  "validate.paste": "Paste",
  "validate.examples": "Examples",
  "validate.drop_hint": "Drop a cvd.json here, or choose a file",
  "validate.result_valid": "Valid",
  "validate.result_invalid": "Invalid",
  "validate.count_errors_one": "{n} error",
  "validate.count_errors_other": "{n} errors",
  "validate.count_warnings_one": "{n} warning",
  "validate.count_warnings_other": "{n} warnings",
  "validate.count_notes_one": "{n} note",
  "validate.count_notes_other": "{n} notes",
  "validate.errors": "Errors",
  "validate.warnings": "Warnings",
  "validate.infos": "Notes",
  "validate.no_issues": "No objections. The document follows the specification.",
  "validate.fix_in_generator": "Open in the generator",
  "validate.explain_this": "Show in plain language",
  "validate.url_title": "Checking a URL",
  "validate.url_body":
    "A browser cannot fetch another domain's file without that domain allowing it, and routing the request through a server here would mean a server that sees which policies you check. It would also be a backend, which this site does not have. Use the command below instead.",

  "explain.title": "Explain a policy",
  "explain.lead": "The same file, written out for someone who does not read JSON.",
  "explain.paste_hint": "Paste a document, drop a file, or load an example.",
  "explain.show_raw": "Show raw data",
  "explain.hide_raw": "Hide raw data",
  "explain.open_in_validator": "Open in the validator",
  "explain.no_rating": "No score, no maturity level, no comparison with other organisations. On purpose.",
  "explain.organization": "Organisation",
  "explain.country": "Country",
  "explain.valid_until": "Valid until",
  "explain.updated": "Last changed",
  "explain.posture": "Security research",
  "explain.statement": "In their words",
  "explain.in_scope_domains": "Domains in scope",
  "explain.in_scope_products": "Products in scope",
  "explain.out_of_scope": "Excluded systems",
  "explain.precedence": "On a conflict",
  "explain.report_to": "Report to",
  "explain.encryption": "Encryption",
  "explain.languages": "Languages",
  "explain.response_within": "Response within",
  "explain.testing_default": "Anything not listed",
  "explain.required_fields": "A report must contain",
  "explain.proof_of_exploitation": "Proof of exploitation",
  "explain.model": "Disclosure",
  "explain.deadline": "Usual deadline",
  "explain.advisories": "Advisories",
  "explain.pgp_available": "PGP available",
  "explain.none": "not stated",
  "explain.hours_one": "{n} hour",
  "explain.hours_other": "{n} hours",
  "explain.days_one": "{n} day",
  "explain.days_other": "{n} days",
  "explain.section.header": "Document",
  "explain.section.research": "Security research",
  "explain.section.scope": "Scope",
  "explain.section.contact": "Contact",
  "explain.section.testing": "Testing rules",
  "explain.section.report_requirements": "Report requirements",
  "explain.section.disclosure": "Disclosure",

  "posture.open.headline": "TESTING WELCOME — within the rules below",
  "posture.open.body":
    "Testing the listed systems is welcome, within the rules you define below. Choose this only if you can act on the reports that arrive.",
  "posture.limited.headline": "LIMITED TESTING — in a defined frame only",
  "posture.limited.body":
    "Testing is permitted only in a clearly drawn frame, such as against a sandbox or with your own test account. Everything else is not permitted.",
  "posture.report_only.headline": "NO INVITATION TO TEST — reports welcome",
  "posture.report_only.body":
    "You do not invite testing, but you accept reports and act on them. That is not a weaker statement than a testing permission — it is an honest one. Most organisations say nothing at all today. This says something.",
  "posture.prohibited.headline": "TESTING RULED OUT",
  "posture.prohibited.body":
    "Testing is ruled out, and reports are either unwanted or go through another route. That is a useful statement too — a researcher then knows not to start here.",
  "posture.recommended": "right for most organisations",

  "precedence.out_overrides_in": "an exclusion wins",
  "precedence.explicit_order": "the last matching entry wins",

  // Bare adjectives: the label supplies the verb ("Everything not listed is"),
  // as it already does in German. With "is allowed" here the select read
  // "Everything not listed is → is prohibited".
  "testing.default.allowed": "allowed",
  "testing.default.prohibited": "prohibited",
  "testing.state.allowed": "allowed",
  "testing.state.prohibited": "prohibited",

  "activity.manual_testing": "Manual testing",
  "activity.automated_scanning": "Automated scanning",
  "activity.fuzzing": "Fuzzing",
  "activity.brute_force": "Brute forcing",
  "activity.dos": "Denial of service",
  "activity.social_engineering": "Social engineering",
  "activity.phishing": "Phishing",
  "activity.physical": "Physical access",
  "activity.spam": "Spam",
  "activity.data_exfiltration": "Exfiltrating data",
  "activity.account_takeover": "Taking over accounts",
  "activity.third_party_pivot": "Pivoting to third parties",
  "activity.supply_chain": "Supply chain",
  "activity.persistence": "Persistence",

  "field.affected_asset": "affected system",
  "field.description": "description",
  "field.reproduction_steps": "steps to reproduce",
  "field.impact": "impact",
  "field.discovery_date": "date of discovery",
  "field.reporter_contact": "your contact details",
  "field.proposed_fix": "proposed fix",

  "proof.required": "required",
  "proof.optional": "optional",
  "proof.prohibited": "not wanted",

  "disclosure.coordinated": "coordinated",
  "disclosure.full_after_deadline": "full disclosure after the deadline",
  "disclosure.vendor_only": "vendor only",
  "disclosure.no_disclosure": "no disclosure",

  "scope.state.in": "in scope",
  "scope.state.out": "excluded",
  "scope.reason.third_party": "operated by a third party",
  "scope.reason.legacy": "legacy system",
  "scope.reason.not_operated": "not operated by us",
  "scope.reason.other": "other",

  "issue.required_missing": "The field {field} is missing.",
  "issue.required_missing.hint": "It is required; without it the document cannot be evaluated.",
  "issue.testing_required": "This posture invites testing, so testing rules are required.",
  "issue.testing_required.hint": "Add a testing section, or choose report_only.",
  "issue.version_unsupported": "Unknown version. Expected {expected}.",
  "issue.version_unsupported.hint": "Consumers must not guess at an unknown version.",
  "issue.enum_invalid": "This value is not defined.",
  "issue.enum_invalid.hint": "Allowed: {allowed}",
  "issue.posture_unknown": "This posture is not defined.",
  "issue.posture_unknown.hint": "Allowed: open, limited, report_only, prohibited.",
  "issue.canonical_not_https": "canonical must be an absolute https URL.",
  "issue.canonical_not_https.hint": "Example: https://example.com/.well-known/cvd.json",
  "issue.pattern_invalid": "This value does not have the expected shape.",
  "issue.format_invalid": "This value is not a valid {format}.",
  "issue.type_invalid": "Expected {expected} here.",
  "issue.max_items": "Too many entries here.",
  "issue.min_items": "At least one entry is required here.",
  "issue.schema_invalid": "This value breaks the rule {keyword}.",
  "issue.json_parse": "This is not valid JSON. {detail}",
  "issue.expires_past": "The expiry date is in the past ({expires}).",
  "issue.expires_past.hint": "Consumers treat this document as if it were not there.",
  "issue.expires_far": "The expiry date is more than twelve months away ({expires}).",
  "issue.expires_far.hint": "A shorter period makes it more likely someone looks at the file again.",
  "issue.canonical_mismatch": "canonical points at {canonical}, but the file was fetched from {retrieved}.",
  "issue.canonical_mismatch.hint": "That may mean the document was copied from somewhere else.",
  "issue.scope_foreign_host": "{pattern} is not at or under {own}, where this document is published.",
  "issue.scope_foreign_host.hint": "A document speaks for the host it sits on and everything below it. Publish one at that host too, or let it point at this document from its own security.txt.",
  "issue.testing_target_foreign": "The rule for {activity} names {target}, which {own} does not cover.",
  "issue.testing_target_foreign.hint": "Tools will ignore this target unless that host points at this document itself.",
  "issue.canonical_has_credentials": "canonical contains a username or password.",
  "issue.canonical_has_credentials.hint": "This file is published. Remove the credentials and treat them as compromised.",
  "issue.scope_pattern_unusable": "{pattern} does not name a host, so it matches nothing.",
  "issue.scope_pattern_unusable.hint": "Write a hostname such as example.com, or *.example.com for everything under it.",
  "issue.posture_contradiction": "The posture {posture} does not invite testing, but testing rules are listed.",
  "issue.posture_contradiction.hint": "Remove the rules, or choose the posture limited or open if you do mean to allow testing.",
  "issue.testing_ignored": "Testing rules are ignored for the posture {posture}.",
  "issue.testing_ignored.hint": "Set the default to prohibited, or choose a posture that invites testing.",
  "issue.testing_default_broad": "Everything not listed is allowed, and nothing is ruled out.",
  "issue.testing_default_broad.hint": "This permits denial of service, social engineering and physical access too. Rule out what you do not want.",
  "issue.condition_targets_empty": "The rule for {activity} has an empty target list.",
  "issue.condition_targets_empty.hint": "An empty list places no restriction at all. Remove it, or name the targets.",
  "issue.string_too_long": "This text is longer than {limit} characters.",
  "issue.string_empty": "This value must not be empty.",
  "issue.number_too_small": "This number is too small (limit {limit}).",
  "issue.number_too_large": "This number is too large (limit {limit}).",
  "issue.scope_private_address": "{pattern} is a private or loopback address.",
  "issue.scope_private_address.hint": "Outside readers cannot reach it, and naming internal addresses in a public file reveals more than it achieves.",
  "generate.step_intake": "Machine-readable intake",
  "generate.intake_question": "Can you receive structured reports?",
  "generate.intake_note": "Optional. A document without this is complete — the contact channels above stay the way people report.",
  "generate.intake_url": "Endpoint that accepts reports",
  "generate.intake_url_help": "Any https URL, yours or a provider's. Nothing is suggested here.",
  "generate.intake_schema": "Schema the endpoint accepts (URL)",
  "generate.intake_profile": "Report profile",
  "generate.intake_anonymous": "Reports without contact details are accepted",
  "generate.intake_max_bytes": "Largest accepted submission (bytes)",
  "generate.intake_attachments": "Attachments",
  "generate.intake_attachments_accepted": "accepted",
  "generate.intake_attachments_after_contact": "after contact",
  "generate.intake_attachments_not_accepted": "not accepted",
  "explain.structured_intake": "Structured submission",
  "explain.intake_offered": "possible",
  "explain.anonymous_reports": "Anonymous reports",
  "common.yes": "yes",
  "common.no": "no",
  "issue.intake_not_https": "The intake endpoint must be an absolute https URL.",
  "issue.intake_not_https.hint": "Reports carry the details of an unfixed vulnerability. They must not travel unencrypted.",
  "issue.intake_has_credentials": "The intake endpoint contains a username or password.",
  "issue.intake_has_credentials.hint": "This file is published. Remove the credentials and treat them as compromised.",
  "issue.intake_third_party": "Reports go to {host}, which is outside {own}.",
  "issue.intake_third_party.hint": "That is normal when a provider runs your intake. Make sure it is the one you chose.",
  "issue.intake_needs_version": "This document uses intake but declares an older version.",
  "issue.intake_needs_version.hint": "Set cvd_policy to {expected} so tools know to read it.",
  "issue.intake_profile_without_schema": "Profile {profile} is named, but no schema URL is given.",
  "issue.intake_profile_without_schema.hint": "Without a schema URL a tool has to assume the profile's defaults.",
  "issue.report_no_reproduction": "No steps to reproduce.",
  "issue.report_no_impact": "No impact given.",
  "issue.report_no_exploitation": "No statement whether this is being exploited.",
  "issue.report_credit_without_name": "Public credit was asked for, but no name was given.",
  "issue.report_share_without_contact": "Sharing contact details was allowed, but none were given.",
  "issue.scope_empty": "The scope lists neither domains nor products.",
  "issue.scope_empty.hint": "A target that nothing matches counts as out of scope.",
  "issue.scope_overlap": "{pattern} overlaps with the earlier entry {other}.",
  "issue.scope_overlap.hint": "Check which entry you want to win, given your precedence setting.",
  "issue.product_support_past": "Support for {name} ended on {date}.",
  "issue.testing_rule_duplicate": "A second rule for {activity} — only the first one applies.",
  "issue.testing_rule_duplicate.hint": "Merge the rules into one. A later, less restrictive duplicate has no effect and misleads anyone reading the file.",
  "issue.testing_unreachable": "The rule for {activity} allows testing, but {target} is out of scope.",
  "issue.testing_unreachable.hint": "The rule can never take effect as written.",
  "issue.contact_missing_encryption": "An open posture without a way to send encrypted reports.",
  "issue.contact_missing_encryption.hint": "Consider publishing a PGP key or an S/MIME certificate.",

  "tools.schema_frozen": "a released version never changes",
  "tools.report_profile": "Report profile",
  "tools.report_profile_note": "what an incoming report looks like",
  "tools.title": "Tools",
  "tools.lead": "Everything needed to implement the format, and everything needed to use the format without this site.",
  "tools.for_implementers": "For implementers",
  "tools.schema": "JSON Schema",
  "tools.library": "Library",
  "tools.cli": "Command line",
  "tools.examples": "Examples",
  "tools.corpus": "Test corpus",
  "tools.action": "GitHub Action",
  "tools.cli_body": "Exit codes: 0 valid, 1 errors, 2 warnings only, 3 not reachable. That makes it usable in CI.",
  "tools.securitytxt": "security.txt",
  "tools.securitytxt_body":
    "The library writes and updates the security.txt too, so an implementer does not have to rebuild RFC 9116 by hand. Updating an existing file leaves comments, field order, blank lines and line endings untouched, and reports whether the field was added, replaced, or already correct.",
  "tools.securitytxt_signed":
    "A clear-signed file cannot be changed without breaking its signature. Both functions report that instead of hiding it, so your tool can tell whoever has to sign the file again.",
  "tools.third_party": "Third-party implementations",
  "tools.third_party_empty": "This list is open. Pull requests welcome.",

  "faq.title": "Questions",
  "faq.q_prohibit": "What if I want to rule out testing?",
  "faq.a_prohibit":
    "Then say so, with posture prohibited or report_only. That is a supported answer, not a failure. A researcher who reads it knows where not to start, and you get reports through the channel you chose instead of through a stranger's blog post.",
  "faq.q_securitytxt": "Does this replace security.txt?",
  "faq.a_securitytxt":
    "No. security.txt stays where it is and keeps doing its job. This format adds one field to it, CVD-Policy, pointing at a file that answers the questions security.txt has no fields for.",
  "faq.q_securitytxt_write": "Can it write my security.txt as well?",
  "faq.a_securitytxt_write":
    "Yes. If you have none, the generator writes a complete one from the same answers: the contact, the expiry date, the languages, the link to your key, and the CVD-Policy line pointing at your cvd.json. If you already have one, drop it in at the first step — you get your own file back with that one line added and everything else exactly as it was, comments and field order included. It is read in your browser and never uploaded.",
  "faq.q_signed": "I sign my security.txt. What happens?",
  "faq.a_signed":
    "RFC 9116 allows a clear-signed security.txt, and any change to such a file breaks its signature. Adding a field and keeping the signature is not possible — not here, not anywhere. This site says so rather than working around it: when the file you hand over carries a signature, you are told at that moment, and again with the result. The changed file is correct; the signature still attached to it is not. Sign it again with the same key before you publish it.",
  "faq.q_cra": "Is this proof of CRA conformity?",
  "faq.a_cra":
    "No. The Cyber Resilience Act asks for processes, not for a JSON file. What this format can do is record parts of what you already decided — contact point, supported versions, disclosure practice — in a form an auditor can read and a tool can check. That is documentation, not conformity.",
  "faq.q_legal": "Does this give me legal certainty?",
  "faq.a_legal":
    "No. A policy document is a unilateral statement. It is not a contract, not consent in the criminal-law sense, and not a waiver of liability. Anyone relying on it does so at their own risk, and the same applies in reverse: publishing one gives you no claim against a researcher. If the legal position matters to your decision, ask a lawyer, not a file format.",
  "faq.q_machine": "Can incoming reports be processed automatically?",
  "faq.a_machine": "Since version 0.2, yes. A policy can name an endpoint that accepts a structured report, the schema that endpoint expects, and whether anonymous reports are accepted. The shape itself is a separate profile, report-0.1: three required fields — title, affected target, description — and everything else optional, because steps to reproduce and impact are not always available and a missing field must never stop someone from reporting. What no tool may do is send a report on its own. A report contains the details of an unfixed vulnerability; where that goes is a decision a person makes, and the specification says so in as many words.",
  "faq.q_versions": "What changed in 0.2, and do I have to redo my file?",
  "faq.a_versions": "No. A released version never changes, and 0.1 documents stay valid and readable — tools that understand 0.2 must keep reading them. Version 0.2 adds exactly one optional field, for the machine-readable intake described above. If you do not need it, there is nothing to do. The generator writes 0.2 because that is the current version; the resulting file says the same as before, plus whatever you filled in.",
  "faq.q_who": "Who runs this site, and on what money?",
  "faq.a_who":
    "Skalvar Technologies UG (haftungsbeschränkt) in Wismar, Germany, runs it. The company earns its money developing IT security software — products you can buy from us and do not need in order to use this format. The generator has a field for any intake URL, with nothing pre-filled and no list to pick from. If that ever changes, this site has stopped being neutral and you should say so publicly.",
  "faq.q_others": "Why not disclose.io, Bugcrowd or a bug bounty platform?",
  "faq.a_others":
    "Those solve a different problem well: running a programme, paying researchers, handling reports in volume. They assume you want a programme. Most organisations do not, and have nothing machine-readable to say instead. This format is the smaller layer underneath: a statement of terms, hosted by you, readable without an account.",
  "faq.q_official": "Is this official or standardised?",
  "faq.a_official":
    "No. It is a draft, version 0.2, published under CC0; 0.1 stays published and valid. The security.txt field is not registered with IANA, and applying for that only makes sense once real use exists. Until then, treat this as a proposal you can adopt, fork or ignore.",
  "faq.q_without": "Can I use this without you?",
  "faq.a_without":
    "Yes, and that is the point. The specification and schema are CC0: copy them, host them, change them. The library and this site are Apache-2.0. Every document the generator produces works without any reference to a provider, and the file lives on your own domain. Nothing here reports back to us.",
  "faq.q_data": "What happens to the data I type in?",
  "faq.a_data":
    "It stays in the tab. The generator keeps your answers in session storage so a reload does not lose them, and that is cleared when you close the tab. There is no server to send anything to.",

  "imprint.title": "Legal notice and privacy",
  "imprint.tmg": "Details pursuant to § 5 TMG",
  "imprint.represented_by": "Represented by",
  "imprint.managing_directors": "Managing directors",
  "imprint.register": "Commercial register",
  "imprint.register_court": "Registering court",
  "imprint.register_number": "Registration number",
  "imprint.vat_title": "VAT identification number",
  "imprint.vat_body": "VAT identification number pursuant to § 27 a UStG",
  "imprint.rstv": "Responsible for the content pursuant to § 18 (2) MStV",
  "imprint.email": "Email",
  "imprint.phone": "Phone",
  "imprint.contact": "Contact",
  "imprint.contact_note": "Given as plain text on purpose. There is no contact form on this site.",
  "imprint.privacy_title": "Privacy",
  "imprint.privacy_body":
    "This site sets no cookies, loads no external resources and runs no analytics. Files you enter into the generator, the validator or the explainer are processed in your browser and are not transmitted. The generator stores your answers in this tab's session storage; the chosen language is kept in local storage. Both can be cleared in your browser at any time.",
  "imprint.hosting_title": "Hosting",
  "imprint.hosting_body":
    "Static hosting in the EU. Server log files may record the usual request data for the purpose of operating and securing the site.",
  "imprint.funding_title": "Funding",
  "imprint.licence_title": "Licences",
} as const;

export type Dict = Record<keyof typeof en, string>;
