// Generated by scripts/sync-spec.mjs. Do not edit.
export const schemas = {
  "0.1": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://cvd-policy.eu/schema/0.1/cvd-policy.schema.json",
    "title": "CVD Policy Format 0.1",
    "description": "Machine-readable statement of how an organisation handles vulnerability reports.",
    "type": "object",
    "required": [
      "cvd_policy",
      "canonical",
      "expires",
      "organization",
      "contact",
      "research",
      "scope",
      "report_requirements"
    ],
    "additionalProperties": true,
    "properties": {
      "cvd_policy": {
        "const": "0.1"
      },
      "canonical": {
        "type": "string",
        "format": "uri",
        "pattern": "^https://"
      },
      "expires": {
        "type": "string",
        "format": "date-time"
      },
      "updated": {
        "type": "string",
        "format": "date"
      },
      "profiles": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "organization": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$"
          },
          "role": {
            "enum": [
              "manufacturer",
              "operator",
              "both",
              "other"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https://"
          }
        },
        "additionalProperties": true
      },
      "contact": {
        "type": "object",
        "required": [
          "channels"
        ],
        "properties": {
          "channels": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "required": [
                "type",
                "value"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "email",
                    "form",
                    "service",
                    "postal"
                  ]
                },
                "value": {
                  "type": "string",
                  "minLength": 1
                },
                "preferred": {
                  "type": "boolean"
                }
              },
              "additionalProperties": true
            }
          },
          "languages": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[a-z]{2}(-[A-Z]{2})?$"
            }
          },
          "encryption": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "type",
                "value"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "pgp",
                    "smime",
                    "other"
                  ]
                },
                "value": {
                  "type": "string",
                  "format": "uri"
                },
                "fingerprint": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            }
          },
          "response_target": {
            "type": "object",
            "properties": {
              "acknowledge_within_hours": {
                "type": "number",
                "exclusiveMinimum": 0
              },
              "update_interval_days": {
                "type": "number",
                "exclusiveMinimum": 0
              }
            },
            "additionalProperties": true
          }
        },
        "additionalProperties": true
      },
      "research": {
        "type": "object",
        "required": [
          "posture"
        ],
        "properties": {
          "posture": {
            "enum": [
              "open",
              "limited",
              "report_only",
              "prohibited"
            ]
          },
          "statement": {
            "type": "string",
            "maxLength": 1000
          }
        },
        "additionalProperties": true
      },
      "scope": {
        "type": "object",
        "required": [
          "precedence"
        ],
        "properties": {
          "precedence": {
            "enum": [
              "out_overrides_in",
              "explicit_order"
            ]
          },
          "web": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "pattern",
                "state"
              ],
              "properties": {
                "pattern": {
                  "type": "string",
                  "minLength": 1
                },
                "state": {
                  "enum": [
                    "in",
                    "out"
                  ]
                },
                "reason": {
                  "enum": [
                    "third_party",
                    "legacy",
                    "not_operated",
                    "other"
                  ]
                },
                "note": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            }
          },
          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "purl": {
                  "type": "string"
                },
                "versions": {
                  "type": "string"
                },
                "supported_until": {
                  "type": "string",
                  "format": "date"
                },
                "sbom": {
                  "type": "string",
                  "format": "uri"
                },
                "state": {
                  "enum": [
                    "in",
                    "out"
                  ]
                }
              },
              "additionalProperties": true
            }
          }
        },
        "additionalProperties": true
      },
      "testing": {
        "type": "object",
        "required": [
          "default"
        ],
        "properties": {
          "default": {
            "enum": [
              "prohibited",
              "allowed"
            ]
          },
          "rules": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "activity",
                "state"
              ],
              "properties": {
                "activity": {
                  "type": "string",
                  "minLength": 1
                },
                "state": {
                  "enum": [
                    "allowed",
                    "prohibited"
                  ]
                },
                "note": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "max_requests_per_second": {
                      "type": "number",
                      "exclusiveMinimum": 0
                    },
                    "user_agent_contains": {
                      "type": "string"
                    },
                    "targets": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "window": {
                      "type": "object",
                      "properties": {
                        "timezone": {
                          "type": "string"
                        },
                        "days": {
                          "type": "array",
                          "items": {
                            "enum": [
                              "mon",
                              "tue",
                              "wed",
                              "thu",
                              "fri",
                              "sat",
                              "sun"
                            ]
                          }
                        },
                        "from": {
                          "type": "string",
                          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$"
                        },
                        "to": {
                          "type": "string",
                          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$"
                        }
                      },
                      "additionalProperties": true
                    },
                    "account_request": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": true
                }
              },
              "additionalProperties": true
            }
          }
        },
        "additionalProperties": true
      },
      "report_requirements": {
        "type": "object",
        "required": [
          "required_fields"
        ],
        "properties": {
          "required_fields": {
            "type": "array",
            "items": {
              "enum": [
                "affected_asset",
                "description",
                "reproduction_steps",
                "impact",
                "discovery_date",
                "reporter_contact",
                "proposed_fix"
              ]
            }
          },
          "proof_of_exploitation": {
            "enum": [
              "required",
              "optional",
              "prohibited"
            ]
          },
          "formats": {
            "type": "array",
            "items": {
              "enum": [
                "text",
                "markdown",
                "pdf",
                "csaf",
                "cvrf",
                "vex"
              ]
            }
          },
          "max_attachment_mb": {
            "type": "number",
            "exclusiveMinimum": 0
          },
          "template": {
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": true
      },
      "disclosure": {
        "type": "object",
        "required": [
          "model"
        ],
        "properties": {
          "model": {
            "enum": [
              "coordinated",
              "full_after_deadline",
              "vendor_only",
              "no_disclosure"
            ]
          },
          "deadline_days": {
            "type": "integer",
            "exclusiveMinimum": 0
          },
          "advisory_url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https://"
          },
          "credit": {
            "enum": [
              "offered",
              "on_request",
              "none"
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "allOf": [
      {
        "if": {
          "required": [
            "research"
          ],
          "properties": {
            "research": {
              "required": [
                "posture"
              ],
              "properties": {
                "posture": {
                  "enum": [
                    "open",
                    "limited"
                  ]
                }
              }
            }
          }
        },
        "then": {
          "required": [
            "testing"
          ]
        }
      },
      {
        "if": {
          "required": [
            "research"
          ],
          "properties": {
            "research": {
              "required": [
                "posture"
              ],
              "properties": {
                "posture": {
                  "enum": [
                    "prohibited",
                    "report_only"
                  ]
                }
              }
            }
          }
        },
        "then": {
          "properties": {
            "testing": {
              "properties": {
                "rules": {
                  "maxItems": 0
                }
              }
            }
          }
        }
      }
    ]
  },
  "0.2": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://cvd-policy.eu/schema/0.2/cvd-policy.schema.json",
    "title": "CVD Policy Format 0.2",
    "description": "Machine-readable statement of how an organisation handles vulnerability reports.",
    "type": "object",
    "required": [
      "cvd_policy",
      "canonical",
      "expires",
      "organization",
      "contact",
      "research",
      "scope",
      "report_requirements"
    ],
    "additionalProperties": true,
    "properties": {
      "cvd_policy": {
        "const": "0.2"
      },
      "canonical": {
        "type": "string",
        "format": "uri",
        "pattern": "^https://"
      },
      "expires": {
        "type": "string",
        "format": "date-time"
      },
      "updated": {
        "type": "string",
        "format": "date"
      },
      "profiles": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "organization": {
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "country": {
            "type": "string",
            "pattern": "^[A-Z]{2}$"
          },
          "role": {
            "enum": [
              "manufacturer",
              "operator",
              "both",
              "other"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https://"
          }
        },
        "additionalProperties": true
      },
      "contact": {
        "type": "object",
        "required": [
          "channels"
        ],
        "properties": {
          "channels": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "object",
              "required": [
                "type",
                "value"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "email",
                    "form",
                    "service",
                    "postal"
                  ]
                },
                "value": {
                  "type": "string",
                  "minLength": 1
                },
                "preferred": {
                  "type": "boolean"
                }
              },
              "additionalProperties": true
            }
          },
          "languages": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[a-z]{2}(-[A-Z]{2})?$"
            }
          },
          "encryption": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "type",
                "value"
              ],
              "properties": {
                "type": {
                  "enum": [
                    "pgp",
                    "smime",
                    "other"
                  ]
                },
                "value": {
                  "type": "string",
                  "format": "uri"
                },
                "fingerprint": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            }
          },
          "response_target": {
            "type": "object",
            "properties": {
              "acknowledge_within_hours": {
                "type": "number",
                "exclusiveMinimum": 0
              },
              "update_interval_days": {
                "type": "number",
                "exclusiveMinimum": 0
              }
            },
            "additionalProperties": true
          }
        },
        "additionalProperties": true
      },
      "research": {
        "type": "object",
        "required": [
          "posture"
        ],
        "properties": {
          "posture": {
            "enum": [
              "open",
              "limited",
              "report_only",
              "prohibited"
            ]
          },
          "statement": {
            "type": "string",
            "maxLength": 1000
          }
        },
        "additionalProperties": true
      },
      "scope": {
        "type": "object",
        "required": [
          "precedence"
        ],
        "properties": {
          "precedence": {
            "enum": [
              "out_overrides_in",
              "explicit_order"
            ]
          },
          "web": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "pattern",
                "state"
              ],
              "properties": {
                "pattern": {
                  "type": "string",
                  "minLength": 1
                },
                "state": {
                  "enum": [
                    "in",
                    "out"
                  ]
                },
                "reason": {
                  "enum": [
                    "third_party",
                    "legacy",
                    "not_operated",
                    "other"
                  ]
                },
                "note": {
                  "type": "string"
                }
              },
              "additionalProperties": true
            }
          },
          "products": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "name"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "purl": {
                  "type": "string"
                },
                "versions": {
                  "type": "string"
                },
                "supported_until": {
                  "type": "string",
                  "format": "date"
                },
                "sbom": {
                  "type": "string",
                  "format": "uri"
                },
                "state": {
                  "enum": [
                    "in",
                    "out"
                  ]
                }
              },
              "additionalProperties": true
            }
          }
        },
        "additionalProperties": true
      },
      "testing": {
        "type": "object",
        "required": [
          "default"
        ],
        "properties": {
          "default": {
            "enum": [
              "prohibited",
              "allowed"
            ]
          },
          "rules": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "activity",
                "state"
              ],
              "properties": {
                "activity": {
                  "type": "string",
                  "minLength": 1
                },
                "state": {
                  "enum": [
                    "allowed",
                    "prohibited"
                  ]
                },
                "note": {
                  "type": "string"
                },
                "conditions": {
                  "type": "object",
                  "properties": {
                    "max_requests_per_second": {
                      "type": "number",
                      "exclusiveMinimum": 0
                    },
                    "user_agent_contains": {
                      "type": "string"
                    },
                    "targets": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "window": {
                      "type": "object",
                      "properties": {
                        "timezone": {
                          "type": "string"
                        },
                        "days": {
                          "type": "array",
                          "items": {
                            "enum": [
                              "mon",
                              "tue",
                              "wed",
                              "thu",
                              "fri",
                              "sat",
                              "sun"
                            ]
                          }
                        },
                        "from": {
                          "type": "string",
                          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$"
                        },
                        "to": {
                          "type": "string",
                          "pattern": "^([01][0-9]|2[0-3]):[0-5][0-9]$"
                        }
                      },
                      "additionalProperties": true
                    },
                    "account_request": {
                      "type": "string"
                    }
                  },
                  "additionalProperties": true
                }
              },
              "additionalProperties": true
            }
          }
        },
        "additionalProperties": true
      },
      "report_requirements": {
        "type": "object",
        "required": [
          "required_fields"
        ],
        "properties": {
          "required_fields": {
            "type": "array",
            "items": {
              "enum": [
                "affected_asset",
                "description",
                "reproduction_steps",
                "impact",
                "discovery_date",
                "reporter_contact",
                "proposed_fix"
              ]
            }
          },
          "proof_of_exploitation": {
            "enum": [
              "required",
              "optional",
              "prohibited"
            ]
          },
          "formats": {
            "type": "array",
            "items": {
              "enum": [
                "text",
                "markdown",
                "pdf",
                "csaf",
                "cvrf",
                "vex"
              ]
            }
          },
          "max_attachment_mb": {
            "type": "number",
            "exclusiveMinimum": 0
          },
          "template": {
            "type": "string",
            "format": "uri"
          },
          "intake": {
            "type": "object",
            "description": "Endpoint that accepts a structured report. Consumers must not submit without a person confirming it.",
            "required": [
              "url"
            ],
            "properties": {
              "url": {
                "type": "string",
                "format": "uri",
                "pattern": "^https://"
              },
              "schema": {
                "type": "string",
                "format": "uri",
                "pattern": "^https://"
              },
              "profile": {
                "type": "string",
                "minLength": 1
              },
              "anonymous": {
                "type": "boolean"
              },
              "max_bytes": {
                "type": "integer",
                "exclusiveMinimum": 0
              },
              "attachments": {
                "enum": [
                  "accepted",
                  "after_contact",
                  "not_accepted"
                ]
              }
            },
            "additionalProperties": true
          }
        },
        "additionalProperties": true
      },
      "disclosure": {
        "type": "object",
        "required": [
          "model"
        ],
        "properties": {
          "model": {
            "enum": [
              "coordinated",
              "full_after_deadline",
              "vendor_only",
              "no_disclosure"
            ]
          },
          "deadline_days": {
            "type": "integer",
            "exclusiveMinimum": 0
          },
          "advisory_url": {
            "type": "string",
            "format": "uri",
            "pattern": "^https://"
          },
          "credit": {
            "enum": [
              "offered",
              "on_request",
              "none"
            ]
          }
        },
        "additionalProperties": true
      }
    },
    "allOf": [
      {
        "if": {
          "required": [
            "research"
          ],
          "properties": {
            "research": {
              "required": [
                "posture"
              ],
              "properties": {
                "posture": {
                  "enum": [
                    "open",
                    "limited"
                  ]
                }
              }
            }
          }
        },
        "then": {
          "required": [
            "testing"
          ]
        }
      },
      {
        "if": {
          "required": [
            "research"
          ],
          "properties": {
            "research": {
              "required": [
                "posture"
              ],
              "properties": {
                "posture": {
                  "enum": [
                    "prohibited",
                    "report_only"
                  ]
                }
              }
            }
          }
        },
        "then": {
          "properties": {
            "testing": {
              "properties": {
                "rules": {
                  "maxItems": 0
                }
              }
            }
          }
        }
      }
    ]
  }
} as const;

export const LATEST_VERSION = "0.2";

export const reportProfile = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cvd-policy.eu/schema/profiles/report-0.1.schema.json",
  "title": "CVD Report 0.1",
  "description": "Baseline shape of a vulnerability report. Three fields are required; everything else helps triage but must never prevent a report. Built on ISO/IEC 29147, and the reporting guidance of CISA, CERT/CC and FIRST.",
  "type": "object",
  "required": [
    "report",
    "title",
    "target",
    "description"
  ],
  "additionalProperties": true,
  "properties": {
    "report": {
      "const": "0.1"
    },
    "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 200,
      "description": "Short technical summary."
    },
    "target": {
      "type": "string",
      "minLength": 1,
      "description": "Product, system or service the finding concerns."
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "description": "The security problem that was observed."
    },
    "reproduction": {
      "type": "string",
      "description": "Steps or proof of concept. Recommended, not required: it is not always available."
    },
    "impact": {
      "type": "string",
      "description": "What an attacker could achieve. Recommended, not required."
    },
    "product": {
      "type": "string"
    },
    "version": {
      "type": "string",
      "description": "Version, build or firmware. `unknown` is a valid answer."
    },
    "endpoint": {
      "type": "string",
      "description": "Where it was found: URL, route, hostname or function."
    },
    "preconditions": {
      "type": "array",
      "description": "What an attacker needs before the finding can be used.",
      "items": {
        "enum": [
          "none",
          "authentication",
          "privileged_role",
          "network_access",
          "local_access",
          "physical_access",
          "user_interaction",
          "specific_configuration"
        ]
      }
    },
    "weakness": {
      "type": "object",
      "description": "The reporter's own assessment. Never a verified classification.",
      "properties": {
        "cwe": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^CWE-[0-9]+$"
          }
        },
        "note": {
          "type": "string"
        }
      },
      "additionalProperties": true
    },
    "identifiers": {
      "type": "object",
      "description": "Existing identifiers, kept apart from the reporter's own assessment.",
      "properties": {
        "cve": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^CVE-[0-9]{4}-[0-9]{4,}$"
          }
        },
        "advisory": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": true
    },
    "expected_behaviour": {
      "type": "string"
    },
    "actual_behaviour": {
      "type": "string"
    },
    "references": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exploitation": {
      "type": "object",
      "description": "Whether the finding is known to be exploited. Three states on purpose: an absent tick must not read as `no`.",
      "required": [
        "state"
      ],
      "properties": {
        "state": {
          "enum": [
            "yes",
            "no",
            "unknown"
          ]
        },
        "evidence": {
          "type": "string",
          "description": "Required when state is `yes`. Remains a reporter statement, not a confirmed finding."
        },
        "observed_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "additionalProperties": true,
      "allOf": [
        {
          "if": {
            "properties": {
              "state": {
                "const": "yes"
              }
            },
            "required": [
              "state"
            ]
          },
          "then": {
            "required": [
              "evidence"
            ]
          }
        }
      ]
    },
    "coordination": {
      "type": "object",
      "description": "Everything already done elsewhere. Optional throughout.",
      "properties": {
        "vendor_contacted": {
          "type": "boolean"
        },
        "first_contact_date": {
          "type": "string",
          "format": "date"
        },
        "communication_summary": {
          "type": "string"
        },
        "publication": {
          "enum": [
            "none_planned",
            "planned",
            "published"
          ]
        },
        "publication_date": {
          "type": "string",
          "format": "date"
        },
        "other_vendors_affected": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": true
    },
    "reporter": {
      "type": "object",
      "description": "Entirely optional. A report without this object must be accepted.",
      "properties": {
        "name": {
          "type": "string"
        },
        "contact": {
          "type": "string"
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^[a-z]{2}(-[A-Z]{2})?$"
          }
        },
        "consent": {
          "type": "object",
          "description": "Three separate decisions. None may be inferred from another, and none defaults to true.",
          "properties": {
            "share_contact_with_affected_party": {
              "type": "boolean"
            },
            "public_credit": {
              "type": "boolean"
            },
            "credit_name": {
              "type": "string"
            }
          },
          "additionalProperties": true
        }
      },
      "additionalProperties": true
    },
    "attachments": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "filename"
        ],
        "properties": {
          "filename": {
            "type": "string",
            "minLength": 1
          },
          "media_type": {
            "type": "string"
          },
          "size_bytes": {
            "type": "integer",
            "exclusiveMinimum": 0
          },
          "sha256": {
            "type": "string",
            "pattern": "^[a-f0-9]{64}$"
          }
        },
        "additionalProperties": true
      }
    },
    "submitted_at": {
      "type": "string",
      "format": "date-time"
    }
  }
} as const;
